{
    #######################################################################
    # DATA INPUTS
    #######################################################################
    "telescopesFile"     : '../test/2020A-telescopes.json',
    "instrumentsFile"    : '../test/2020A-instruments.json',
    "moonPhasesFile"     : '../test/2020A-moon-phases.json',
    "telShutdownsFile"   : '../test/2020A-tel-shutdowns.json',
    "instrShutdownsFile" : '../test/2020A-instr-shutdowns.json',
    "programsFile"       : '../test/2020A-programs.json',




    #######################################################################
    # SCHEDULING CONSTANTS
    #######################################################################
    
    #Minimal block size
    #todo: these could go in each telescopes
    "slotPerc": 0.25,


    #######################################################################
    # SORTING PARAMETERS
    #######################################################################

    #order score mult if block type is cadence
    "blockOrderCadenceMult": 1.25,

    #plus or minus adjustment factor to order score (ie 0.10 is +- 10%)
    "blockOrderRandomMult": 0.10,

    #order score mult by moonIndex type
    "blockOrderMoonTypeMult":
    {
        'D'    : 1.5,
        'G-DL' : 1.25,
        'G-DE' : 1.25,
        'B'    : 1.0
    },



    #######################################################################
    # SCORING PARAMETERS
    #######################################################################
    #todo: should we change this to assume a scheduled block is given a perfect score of 1 and scoring only multiplies
    # by a factor < 1.0 for less than perfect things?

    # score added for slot match with date range preference
    # P = preferred, A = acceptable, N = neutral, X = avoid
    # NOTE: A small non-zero score is given to X to differentiate it from slots that are absolutely not allowed.
    "moonDatePrefScore":
    {
        'P': 10,
        'A': 5,
        'N': 2,
        'X': 0.1
    },

    #score added for slot match with requested (TAC scheduled) moon phase
    "reqMoonIndexScore": 15,

    #Score multiplier for scheduling a block in the requested date (block['reqDate'])
    "reqDateMult": 1.5,

    #Score multiplier for scheduling a block in the requested portion of the night (block['reqSlot'])
    "reqPortionMult": 1.25,

    #Slot score percentage difference from top slot score value for it to be considered for pool of random slots to choose from.
    # value from 0 to 1.0 where 0.0 means keep only the top scoring slots, 0.20 means choose from top 20% of values, and 1.0 means chose randomly from all slots
    "slotScoreTopPerc": 0.25,


}