{
    #######################################################################
    # DATA INPUTS
    #######################################################################
    "telescopesFile"     : '../test/test-data-telescopes-2019B.json',
    "instrumentsFile"    : '../test/test-data-instruments-2019B.json',
    "moonPhasesFile"     : '../test/test-data-moon-phases-2019B.json',
    "telShutdownsFile"   : '../test/test-data-tel-shutdowns-2019B.json',
    "instrShutdownsFile" : '../test/test-data-instr-shutdowns-2019B.json',
    "programsFile"       : '../test/test-data-programs-2019B.json',
#    "blocksFile"         : '../test/test-data-blocks-2019B.json',



    #######################################################################
    # SCHEDULING CONSTANTS
    #######################################################################
    
    #Minimal block size
    #todo: these could go in each telescopes
    "slotPerc": 0.25,


    #######################################################################
    # SCORING PARAMETERS
    #######################################################################
    #todo: should we change this to assume a scheduled block is given a perfect score of 1 and scoring only multiplies
    # by a factor < 1.0 for less than perfect things?

    # score added for slot match with date range preference
    # P = preferred, A = acceptable, N = neutral, X = avoid
    # NOTE: A small non-zero score is given to X to differentiate it from slots that are absolutely not allowed.
    "moonDatePrefScore":
    {
        'P': 10,
        'A': 5,
        'N': 2,
        'X': 0.1
    },

    #Slot score percentage difference from top slot score value for it to be considered for pool of random slots to choose from.
    # value from 0 to 1.0 where 0.0 means keep only the top scoring slots, 0.20 means choose from top 20% of values, and 1.0 means chose randomly from all slots
    "slotScoreTopPerc": 0.20,

    #Score multiplier for scheduling a block in the requested date (block['reqDate'])
    "reqDateMult": 1.5,

    #Score multiplier for scheduling a block in the requested portion of the night (block['reqSlot'])
    "reqPortionMult": 1.25,
}